@startuml

	class Additives << enumeration >> {
        None
        FoodColoring
        Preservatives
        Antioxidants
        FlavorEnhancer
        Phosphate
        Sulphureted
        Waxed
        Blackend
        Sweetener
        Phenylalanine
        Taurine
        NitritePicklingSalt
        Caffeinated
        Quinine
        MilkProtein
	}

        class Allergens << enumeration >> {
        None
        Gluten
        Shellfish
        Eggs
        Fish
        Peanuts
        Soy
        Milk
        Nuts
        Celery
        Mustard
        Sesame
        Sulfur
        Lupine
        Mollusk
    }



@enduml

