@startuml

package ".NET MAUI APP" as App {

}
package Core {

}

package Ports {
		interface IDataSource<TId, TEntity> {
		TEntity Retrieve(TId id)
		TEntity[] RetrieveAll()
	}

	package Additives  {
	}

	package Allergens  {

    }

	class Category << enumeration >> {
		none
		dish
		sidedish
		dessert
		soup
	}

	interface IMeal {
		{field} Date date
		{field} String name
		{field} IPrice IPrice
		{field} Allergens allergens
		{field} Additives additives
		{field} Category category
		{field} URL image		
	}

	interface IPrice {
		double Students
		double Employees
		double Others
	}


}

package Infrastructure {
        class MealDataSource {
        IMeal Retrieve(int id)
        IMeal[] RetrieveAll()        
        }

        class Meal {}

        class Price {}

        class OpenMensaAPI {
                Meal[] GetTodaysMeals(int id)

        }

}


IMeal -- Category
IMeal -- Allergens
IMeal -- Additives
IMeal -- IPrice
IDataSource <|-- MealDataSource
IMeal <|-- Meal
IPrice <|-- Price
Meal -- Price
MealDataSource -- Meal
'IGetMealsService -- MensaView 
'IDataSource -- GetMealsService
'GetMealsService -- IDataSource
MealDataSource -- OpenMensaAPI
OpenMensaAPI -- Meal
MealDataSource ..> Core : inject IDataSource
Core ..> App : inject IGetMealsService

@enduml

