@startuml

package Ports {


        package IMealCollection {
        }

        interface IMealQuery {
                int mensa
                Date date
        }

        interface IGetMealsService {
               IMealCollection[] Execute(IMealQuery query)
        }

}

package Infrastructure {

}

package Core {
}

package ".NET MAUI APP" as App {
class "Mensa UI" as MensaView {
	MensaViewModel viewModel
}
class MensaViewModel {
	IMealCollection[] meals
}
class MealQuery {

}
}

IGetMealsService -- IMealCollection
IGetMealsService -- IMealQuery
MensaView o-- MensaViewModel
MensaViewModel -- IMealCollection
IMealQuery <|-- MealQuery
MensaView -- MealQuery
'IGetMealsService -- MensaView 
'IDataSource -- GetMealsService
Infrastructure ..> Core : inject IDataSource
Core ..> MensaView : inject IGetMealsService
MensaView -- IGetMealsService
Core <|-- IGetMealsService


@enduml

