@startuml

package ".NET MAUI APP" as App {

}

package Ports {

	class Category << enumeration >> {
		none
		dish
		sidedish
		dessert
		soup
	}

	package IMeal {
	}


        interface IMealCollection {
                Category category
                IMeal[] IMeals
        }

        interface IMealQuery {
                int mensa
                Date date
        }

        interface IGetMealsService {
               IMealCollection[] Execute(IMealQuery query)
        }

        		interface IDataSource<TId, TEntity> {
		TEntity Retrieve(TId id)
		TEntity[] RetrieveAll()
	}


}

package Infrastructure {

}

package Core {
        class GetMealsService {

        }

        class MealCollection {

        }
}

IGetMealsService -- IMealCollection
IGetMealsService -- IMealQuery
IMealCollection -- IMeal
IMealCollection -- Category
IMeal -- Category
IMealCollection <|-- MealCollection
IGetMealsService <|-- GetMealsService
'IGetMealsService -- MensaView 
'IDataSource ..> GetMealsService : injected
'IDataSource -- GetMealsService
GetMealsService -- MealCollection
'GetMealsService -- IDataSource
GetMealsService -- IMealQuery
Infrastructure ..> GetMealsService : inject IDataSource
GetMealsService ..> App : inject IGetMealsService
IDataSource <|-- Infrastructure

@enduml

