@startsalt
{+
Edit ""         "" <b>World Clock ""           "" <&plus>
--
{
    .
    <&clock> | Cupertino | ""                "" <&chevron-right>
    . | today, 3 hours behind | .
    ----
    <&clock> | London | ""                "" <&chevron-right>
    . | today, 5 hours ahead | .
    .
    .
    .
    .
    .
    .
    .
    .
    .
    .
    .
    .
    .    
}
{/ <b> World Clock | Alarm | Stop Watch | Timer }
}

@endsalt

