@startgantt
[Projektmanagement] lasts 42 days
[Qualitätssicherung] lasts 42 days
[Idee und Vision] lasts 5 days
[Inception Gate] happens at [Idee und Vision]'s end
[Anforderungen] lasts 5 days
[Anforderungen] starts at [Inception Gate]'s end
[Architektur] lasts 5 days
[Architektur] starts at [Anforderungen]'s end
[Benutzerschnittstelle] lasts 5 days
[Benutzerschnittstelle] starts at [Architektur]'s end
[Elaboration Gate] happens at [Benutzerschnittstelle]'s end
[Grundgerüst] lasts 5 days
[Grundgerüst] starts at [Elaboration Gate]'s end
[Quiz] lasts 5 days
[Quiz] starts at [Grundgerüst]'s end
[Mensa UI und Settings] lasts 5 days
[Mensa UI und Settings] starts at [Grundgerüst]'s end
[Mensa Geschäftslogik] lasts 5 days
[Mensa Geschäftslogik] starts at [Mensa UI und Settings]'s end
[Veranstaltungen] lasts 5 days
[Veranstaltungen] starts at [Grundgerüst]'s end
[Professoren] lasts 5 days
[Professoren] starts at [Grundgerüst]'s end
[Construction Gate] happens at [Mensa Geschäftslogik]'s end
[Inbetriebnahme] lasts 5 days
[Inbetriebnahme] starts at [Construction Gate]'s end
@endgantt
