@startuml

abstract class Beverage {
	description
	getDescription()
	{abstract} cost()


}

class HouseBlend {
	cost()
}

class DarkRoast {
	cost()
}

class Decaf {
	cost()
}

class Espresso {
	cost()
}

class HouseBlendWithSteamedMilkandMocha {
	cost()
}

class DarkRoastWithSteamedMilkandMocha {
	cost()
}

class DecafWithSteamedMilkandMocha {
	cost()
}

class EspressoWithSteamedMilkandMocha {
	cost()
}

class HouseBlendWithSteamedMilkandCaramel {
	cost()
}

class DarkRoastWithSteamedMilkandCaramel {
	cost()
}

class DecafWithSteamedMilkandCaramel {
	cost()
}

class EspressoWithSteamedMilkandCaramel {
	cost()
}

class "..." as More {
	cost()
}


Beverage <|-- HouseBlend
Beverage <|-- DarkRoast
Beverage <|-- Decaf
Beverage <|-- Espresso
Beverage <|-- HouseBlendWithSteamedMilkandMocha
Beverage <|-- DarkRoastWithSteamedMilkandMocha
Beverage <|-- DecafWithSteamedMilkandMocha
Beverage <|-- EspressoWithSteamedMilkandMocha
Beverage <|-- HouseBlendWithSteamedMilkandCaramel
Beverage <|-- DarkRoastWithSteamedMilkandCaramel
Beverage <|-- DecafWithSteamedMilkandCaramel
Beverage <|-- EspressoWithSteamedMilkandCaramel
Beverage <|-- More
@enduml

