@startuml
left to right direction

actor :AC01 Studierender: as AC01
actor :AC02 Dozent: as AC02
actor :AC03 Mitarbeiter: as AC03
' actor :AC04 Redakteur: as AC04

' rectangle "SYS03 / SYS04" {
(UC01 Stundenplan abrufen) as (UC01)
(UC02 Veranstaltung exportieren) as (UC02)
(UC03 Mensaplan abrufen) as (UC03)
(UC04 Quizfrage ansehen) as (UC04)
(UC05 Quizfrage beantworten) as (UC05)
(UC06 Statistik ansehen) as (UC06)
(UC07 Informieren über Professoren) as (UC07)
(UC08 Anwendung personalisieren) as (UC08)
(UCS08-01 Unverträglichkeiten erfassen) as (UCS0801) << Slice >>
(UCS08-02 Semester einstellen) as (UCS0802) << Slice >>
(UCS08-03 Statusgruppe einstellen) as (UCS0803) << Slice >>


'}

AC03 --> (UC03)
AC03 --> (UC08)
AC02 --> (UC01)
AC02 --> (UC02)
AC02 --> (UC03)
AC02 --> (UC08)
AC01 --> (UC01)
AC01 --> (UC02)
AC01 --> (UC03)
AC01 --> (UC04)
AC01 --> (UC05)
AC01 --> (UC06)
AC01 --> (UC07)
AC01 --> (UC08)
UC08 --> (UCS0801) 
UC08 --> (UCS0802) 
UC08 --> (UCS0803) 

@enduml