@startuml
left to right direction

actor :AC01 Nutzer: as AC01

(UC01 Zugang konfigurieren) as (UC01)
(UC02 Alarmierung) as (UC02)
(UC03 Status einsehen) as (UC03)

AC01 --> (UC01)
AC01 --> (UC02)
AC01 --> (UC03)

@enduml