@startuml

actor :AC01 Nutzer: as AC01
actor :AC02 Administrator: as AC02

package "Mobile Apps" {
  component [SYS01 Wearable App] as SYS01
}

package "Hoefliger Backend" {
  component [SYS02 Alarm Backend] as SYS02
  component [SYS03 Microsoft Exchange Server 2016] as SYS03
}

package "External Backend" {
  component [SYS04 Firebase] as SYS04
}


AC01 - SYS01
AC02 - SYS02
SYS01 -> SYS02
SYS02 -> SYS03
SYS02 -> SYS04
SYS04 .. SYS01
@enduml