@startuml

actor :AC01 Studierender: as AC01
actor :AC02 Dozent: as AC02
actor :AC03 Mitarbeiter: as AC03

package "Mobile Apps" {
  component [SYS01 iOS App] as SYS03
  component [SYS02 Android App] as SYS04
}

package "External Backend I" {
  component [EXT01 Mensa Server] as SYS06
}
 
AC01 - SYS03
AC01 - SYS04
AC02 - SYS03
AC02 - SYS04
AC03 - SYS03
AC03 - SYS04
SYS03 ..> SYS06 : REST/JSON
SYS04 ..> SYS06 : REST/JSON

@enduml