
@startmindmap
* .
** HelloWorld
*** App.xaml
*** App.xaml.cs
*** AppShell.xaml
*** AppShell.xaml.cs
*** HelloWorld.csproj
*** MainPage.xaml
*** MainPage.xaml.cs
*** MauiProgram.cs
*** Platforms
**** Android
***** AndroidManifest.xml
***** MainActivity.cs
***** MainApplication.cs
***** Resources
****** values
******* colors.xml
**** MacCatalyst
***** AppDelegate.cs
***** Info.plist
***** Program.cs
**** Tizen
***** Main.cs
***** tizen-manifest.xml
**** Windows
***** App.xaml
***** App.xaml.cs
***** Package.appxmanifest
***** app.manifest
**** iOS
***** AppDelegate.cs
***** Info.plist
***** Program.cs
*** Properties
**** launchSettings.json
*** Resources
**** AppIcon
**** Fonts
**** Images
**** Raw
**** Splash
**** Styles
** HelloWorld.sln
** bin
** obj
@endmindmap
