@startuml

class Explainer
{
    ITransformer Model
    IDataView Data
    ScenarioType Scenario
    string LabelColumnName
    string GetPermutationFeatureImportance(Metric metric)
    string GetCustomExplanationA()
    ...()
}


@enduml

