@startjson
{
  "Scenario": [
    "Classification",
    "Regression",
    "Recommendation",
    "ImageClassification",
    "ObjectDetection",
    "Forecasting",
    "TextClassification",
    "SentenceSimilarity",
    "QuestionAnswer",
    "NamedEntityRecognition"
    ],
  "DataSource": "...",
  "Environment": "...",
  "TrainingOption": {
    "AvailableTrainers": [
      "LBFGS",
      "LGBM",
      "SDCA",
      "FASTTREE",
      "RANDOMFOREST"
    ],
    "ValidationOption": [
        {
      "Type": "TrainValidateSplitValidationOption",
      "SplitRatio": "..."
       },
       {
      "Type": "CrossValidationValidationOption",
      "NumberOfFolds": "..."
       },
       {
      "Type": "FileValidationOption",
      "FilePath": "..."
       }
    ]
  }
}
@endjson

