@startjson
{
  "Scenario": "Classification",
  "DataSource": {
    "Version": 3,
    "EscapeCharacter": "\"",
    "ReadMultiLines": false
  },
  "TrainingOption": {
    "Version": 2,
    "Subsampling": false,
    "Type": "ClassificationTrainingOption",
    "TrainingTime": 20,
    "LabelColumn": "col1",
    "ValidationOption": {
      "Version": 0,
      "Type": "TrainValidateSplitValidationOption",
      "SplitRatio": 0.1
    }
  }
}
@endjson

