@startuml

package "Core Ports" <<Rectangle>> {
interface Track {
	String artistName
   	String trackName
  	String collectionName
	int trackNumber
	int discNumber
  	String artworkUrl
}


interface TrackCollection {
	String name
	Track[] tracks
}
}

package "UI" <<Rectangle>> {
class CollectionViewModel {
	String name
	TrackViewModel[] tracks
}

class TrackViewModel {
	String title
	String subtitle
	URL image	
}
}

TrackCollection "1" - "1..*" Track
CollectionViewModel "1" - "1..*" TrackViewModel

@enduml

