@startjson
{"id":278523,"name":"Gegrilltes H\u00e4hnchenbrustfilet in Frischk\u00e4se-Lauchso\u00dfe (A, A1, G), dazu Kohlrabi und Kartoffelb\u00e4llchen","notes":["Glutenhaltiges Getreide (A)","Weizen (A1)","Milch\/Milchzucker (Laktose) (G)"],"prices":{"Studierende":3.6,"Bedienstete":6.55},"category":"Angebot 1","image":"\/\/static.studentenwerk-dresden.de\/bilder\/mensen\/studentenwerk-dresden-lieber-mensen-gehen.jpg","url":"https:\/\/www.studentenwerk-dresden.de\/mensen\/speiseplan\/details-278523.html"}
@endjson

