@startjson
{"id":279563,"name":"Ungarische Gulaschsuppe ( A, A1, J)","notes":["enth\u00e4lt Rindfleisch","mit Antioxydationsmittel (3)","mit S\u00fc\u00dfungsmittel (9)","Glutenhaltiges Getreide (A)","Weizen (A1)","Senf (J)"],"prices":{"Studierende":2.16,"Bedienstete":3.93},"category":"Suppen","image":"\/\/static.studentenwerk-dresden.de\/bilder\/lieber-mensen-gehen.jpg","url":"https:\/\/www.studentenwerk-dresden.de\/mensen\/speiseplan\/details-279563.html"}
@endjson

