@startuml

package "Platform dependent (iOS)" {
[iOS UI] as UI1 <<SwiftUI>>
[iOS Infrastructure] as Infra3 <<Swift>>
[iOS Infrastructure Adapters] as Adapt1 <<Swift>>
}
package "Platform independent" {
[App Core] as Core <<Kotlin>>
[UI Ports] as Ports4 <<Kotlin>>
[Infrastructure Ports] as Ports3 <<Kotlin>>
[Shared Infrastructure] as Infra1 <<Kotlin>>
}
package "Platform dependent (Android)" {
[Android UI] as UI2 <<Jetpack Compose>>
[Android Infrastructure] as Infra2 <<Kotlin>>
[Android Infrastructure Adapters] as Adapt2 <<Kotlin>>
}

UI1 --> Ports4 
UI2 --> Ports4 
UI1 ..> Core : configure
UI2 ..> Core : configure
UI1 ..> Adapt1 : configure
UI2 ..> Adapt2 : configure
UI1 ..> Infra1 : configure
UI2 ..> Infra1 : configure
Core ..> Ports4
Core --> Ports3 
Infra1 --> Ports3
Infra3 --> Ports3
Infra2 --> Ports3
Adapt1 --> Infra3
Adapt2 --> Infra2
@enduml

