@startuml

[iOS UI] as UI1 <<SwiftUI>>
[Android UI] as UI2 <<Jetpack Compose>>
[App Core] as Core <<Kotlin>>
[Shared Infrastructure] as Infra1 <<Kotlin>>
[Android Infrastructure] as Infra2 <<Kotlin>>
[iOS Infrastructure] as Infra3 <<Swift>>
[iOS Infrastructure Ports] as Ports1 <<Swift>>
[iOS UI Ports] as Ports2 <<Swift>>
[Android Infrastructure Ports] as Ports3 <<Kotlin>>
[Android UI Ports] as Ports4 <<Kotlin>>


UI1 ..> Ports2 : SPM
UI2 ..> Ports4 : gradle
Ports2 ..> Core : SPM
Ports4 ..> Core : gradle
Core ..> Ports1 : SPM
Core ..> Ports3 : gradle
Ports1 ..> Infra1 : SPM
Ports1 ..> Infra3 : SPM
Ports3 ..> Infra1 : gradle
Ports3 ..> Infra2 : gradle
@enduml

