@startuml

component Driving1 [
test 
adapter
] 
component Driving2 [
GUI
adapter
] 
/'component Driving3 [
http
adapter
] '/
() "user-side API" as Driving
() "data-side API" as Driven

together {
component Driving4 [
app-to-app 
adapter
] 
component App [
Application (⬡)
]
component Driven1 [
DB access
service
] 
}
component Driven2 [
mock in-memory
database
] 

Driving - App
Driven - App
Driving1 ..> Driving 
Driving2 ..> Driving 
'Driving3 ..> Driving 
Driving4 ..> Driving 
Driven1 ..> Driven
Driven2 ..> Driven
@enduml

