@startsalt
title Veranstaltungen
header SCR01
footer Low-fi prototype (wireframe)
{+
{
    .
    "<&magnifying-glass> Suchbegriff"
    ==
    === 3. Semester 
    ==
    **Betriebssysteme VL**
    //Hörsaal HAM 5 (Nunkesser)//
    Mi 10:30
    --
    **Netzwerke VL**
    //Hörsaal HAM 5 (Nunkesser)//
    Mi 13:00
    ==
    === 7. Semester 
    ==
    .
    .
    .
    .
    .
    .
    .
    .
    .
    .
    .
    .
    .
    .
    .
    .
    .
    .
    .
    .
    .
}
{/ <b>Stundenplan | Mensa | Quiz | Profs | Einstellungen }
}
@endsalt

