@startsalt
title Veranstaltungen
header SCR01
footer Low-fi prototype (wireframe)
{+
{
    .
    "<&magnifying-glass> Suchbegriff"
    ==
    === 3. Semester 
    ==
    **Betriebssysteme VL**
    //Hörsaal HAM 5 (Nunkesser)//
    Mi 10:30
    --
    . . .
    ==
    === 7. Semester 
    ==
    **Advanced App Development VL**
    //H4.3-E00-110 (Nunkesser)//
    Mo 08:30
    --
    . . .
    --
}
{/ <b>Kurse | Mensa | Quiz | Profs | <&cog> }
}
@endsalt

