@startsalt
title Mensa
header SCR02
footer Low-fi prototype (wireframe)
{+
{
    == | * | * 
    === Essen | *
    == | * | *
    <&image> | Big Veggie Burger | <&chevron-right>
    . | 2,80 € | .
    == | * | *
    === Suppen | *
    == | * | *
    <&image> | Kichererbsensuppe mit Nudeln | <&chevron-right>
    . | 1,80 € | .
    == | * | *
    === Beilagen | *
    == | * | *
    <&image> | Kartoffelgnocchi | <&chevron-right>
    . | 0,60 € | .
    == | * | *
    === Desserts | *
    == | * | *
    <&image> | Schokopudding | <&chevron-right>
    . | 1,20 € | .
    .
    .
    .
    .
}
{/ Kurse | <b>Mensa | Quiz | Profs | Einstellungen }
}
@endsalt

