@startsalt
{+
""            "" Quiz ""           "" <&info>
--
{
    .
    .
    .
    .
    .
    === Fragetext
    .
    .
    .
    .
    .
    [Falsch] | [ Wahr ]
    [Überspringen] | *
}
{/ Kurse | Mensa | <b> Quiz | Profs | <&cog> }
}

@endsalt

