@startsalt
title Quiz <&info>
header SCR03
footer Low-fi prototype (wireframe)
{+
{
    .
    .
    .
    .
    .
    === Fragetext
    .
    .
    .
    .
    .
    [Falsch] | [ Wahr ]
    [Überspringen] | *
}
{/ Kurse | Mensa | <b> Quiz | Profs | Einstellungen }
}

@endsalt

