@startsalt
{+
""          "" Professoren
--
{
    .
    "Name" | <&magnifying-glass>
    Prof. Dr. Bernasconi | ""          "" <&chevron-right>
    Mobile Computing | .
    ----
    Prof. Dr. Moriarty | ""          "" <&chevron-right>
    Mathematik | .
    .
    .
    .
    .
    .
    .
    .    
}
{/ Kurse | Mensa | Quiz | <b> Profs | <&cog> }
}

@endsalt

