@startsalt
{+
""         "" Einstellungen
--
{
    .
    Statusgruppe | ""           "" <&chevron-right>
    ----
    Allergene | ""           "" <&chevron-right>
    ----
    Zusatzstoffe | ""           "" <&chevron-right>
    .
    .
    .
    .
    .
    .
    .
    .
    .      
}
{/ Kurse | Mensa | Quiz | Profs | <b> <&cog> }
}

@endsalt

