@startsalt
title Einstellungen
header SCR05
footer Low-fi prototype (wireframe)
{+
{
    .
    Statusgruppe | <&chevron-right>
    ----
    Allergene | <&chevron-right>
    ----
    Zusatzstoffe | <&chevron-right>
    .
    .
    .
    .
    .
    .
    .
    .
    .      
}
{/ Kurse | Mensa | Quiz | Profs | <b> <&cog> }
}

@endsalt

