@startsalt
{+
""           "" Statistik
--
{
    .    
    Bearbeitete Fragen | ""          "" 10
    ----
    Richtig beantwortet | ""           "" 7
    ----
    Falsch beantwortet | ""           "" 1
    ----
    Übersprungen | ""           "" 2
    .
    .
    .
    .
    .
    .
}
{/ Kurse | Mensa | <b> Quiz | Profs | <&cog> }
}

@endsalt

