@startuml

state "MySplashActivity" as SCR01
state "MainMenuActivity" as SCR02
state "SimpleInputActivity" as SCR03
state "SortimentActivity" as SCR04
state "InventurActivity" as SCR05
state "InventurGewichtActivity" as SCR06
state "SettingsActivity" as SCR07

[*] --> SCR01
SCR01 --> SCR02
SCR02 --> SCR03 : tap[btnEtikettendruck]
SCR02 --> SCR03 : tap[btnWarenumlagerung]
SCR02 --> SCR04 : tap[btnSortimentsliste]
SCR02 --> SCR03 : tap[btnMdeLieferschein]
SCR02 --> SCR03 : tap[btnMdeBestand]
SCR02 --> SCR05 : tap[btnInventurStueck]
SCR02 --> SCR06 : tap[btnInventurGewicht]
SCR02 --> SCR07 : tap[Settings]
@enduml