@startuml

participant "MySplashActivity" as SCR01
participant "MainMenuActivity" as SCR02
participant "Settings" as SCR03

autonumber
SCR01->SCR01: onCreate
activate SCR01
deactivate SCR01
SCR01->SCR01: onPostResume
activate SCR01
SCR01->SCR01: checkOK
activate SCR01
SCR01->SCR01: checkPermissions
activate SCR01
SCR01 --> SCR03: MANAGE_OVERLAY_PERMISSION
note left
if overlay permission
is not given
end note
deactivate SCR01
SCR01->SCR01: continueMainActivity
activate SCR01
...2500 ms later...
SCR01->SCR02: new
deactivate SCR01
deactivate SCR01
deactivate SCR01
@enduml