
@startmindmap
* .
** StudyCompanion
' *** App.xaml
' *** App.xaml.cs
' *** AppShell.xaml
' *** AppShell.xaml.cs
' *** StudyCompanion.csproj
' *** MainPage.xaml
' *** MainPage.xaml.cs
*** MauiProgram.cs
' *** ServiceHelper.cs
' *** LocalizeExtension.cs
' *** Platforms
' **** Android
' **** MacCatalyst
' **** Tizen
' **** Windows
' **** iOS
' *** Properties
'**** launchSettings.json
'*** Common
'**** SectionViewModel.cs
' *** Tabs
' ' **** Courses
' ' ***** CoursesPage.xaml
' ' ***** CoursesPage.xaml.cs
' **** Mensa
' ***** MealQuery.cs
' ***** MensaPage.xaml
' ***** MensaPage.xaml.cs
' ***** MensaViewModel.cs
' ***** PriceConverter.cs
' ' **** Profs
' ' ***** ProfsPage.xaml
' ' ***** ProfsPage.xaml.cs
' ' **** Quiz
' ' ***** QuizPage.xaml
' ' ***** QuizPage.xaml.cs
' ' ***** QuizStatisticsPage.xaml
' ' ***** QuizStatisticsPage.xaml.cs
' ' ***** QuizViewModel.cs
' **** Settings
' ' ***** AcknowledgementsPage.xaml
' ' ***** AcknowledgementsPage.xaml.cs
' ***** AdditivesPage.xaml
' ***** AdditivesPage.xaml.cs
' ***** AdditivesViewModel.cs
' ***** AllergensPage.xaml
' ***** AllergensPage.xaml.cs
' ***** AllergensViewModel.cs
' ***** Settings.cs
' ***** SettingsPage.xaml
' ***** SettingsPage.xaml.cs
' ***** SettingsViewModel.cs
' *** Resources
' ' **** AppIcon
' ' **** Fonts
' ' **** Images
' ' ***** courses.svg
' ' ***** mensa.svg
' ' ***** profs.svg
' ' ***** quiz.svg
' ' ***** settings.svg
' ' ***** statistics.svg
' ' **** Raw
' ' ***** acknowledgements.html
' ' **** Splash
' **** Strings
' ***** AppResources.resx
' ' ***** AppResources.Designer.cs
' ***** AppResources.de.resx
' **** Styles
' ** StudyCompanion.sln
'** bin
'** obj
** StudyCompanion.Core
'** StudyCompanion.Core.Mock
*** OpenMensaGetMealsService.cs
*** MealCollection.cs
** StudyCompanion.Core.Tests
*** UnitTest1.cs
** StudyCompanion.Infra
*** Canteen.cs
*** Day.cs
*** Extensions.cs
*** Meal.cs
*** OpenMensaAPI.cs
*** OpenMensaMeal.cs
*** OpenMensaMealDataSource.cs
*** Price.cs
*** StudyCompanion.Infra.csproj
'** StudyCompanion.Infra.Mock
'*** MockMealDataSource.cs
** StudyCompanion.Infra.Tests
*** UnitTest1.cs
** StudyCompanion.Ports
' *** Additives.cs
' *** Allergens.cs
' *** Category.cs
*** IDataSource.cs
' *** IGetMealsService.cs
' *** IMeal.cs
' *** IMealCollection.cs
' *** IMealQuery.cs
' *** IPrice.cs
' *** IService.cs
'*** IQuestion.cs
'*** IYesNoQuestion.cs
@endmindmap
